### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by gutihernandez** [timhutton/mobius-transforms#1]
Hi Tim,

I found your code extremely helpful to analyze and characterize Mobius transformations!

I have used your code in an **academic research** and thus I **would like to cite** this repository. 

Do you have any preference that I should be using when **citing your repository** or **any conditions** that you may want to share?

Thanks

**Comment by timhutton** [comment]
Hello,

Thanks for the kind words. Please cite it in any way you like.

I'll put the code itself under a GPL3 license but this doesn't affect your citation.

Regards,

Tim

**Comment by gutihernandez** [comment]
Thanks a lot for your quick reply!
