### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by danilw** [timhutton/mobius-transforms#7]
> GPL-3.0 license

I suppose, author expect people to contact them personally for "commercial/close source" usage of this logic/code?

I was expecting to see MIT license, but it GPL. (I was thinking to use this code in my MIT-licensed software, but I can not look like)

**Comment by timhutton** [comment]
Your understanding of the GPL is correct. The aim of it is to prevent the scenario where code is taken by a commercial entity and then improved on without those improvements being shared with the community.
